name: Publish Website
on: push
  branches: [ "main" ]
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v3
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        ftp-server: ftp://${{ secrets.ftp_host }}/
        ftp-username: ${{ secrets.ftp_user }}
        local-dir: ./
        ftp-password: ${{ secrets.ftp_password }}